apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: learning-go-api-iac-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Takapiwanashe/learning-go-api-iac.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts
     directory
    !/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: angi-helloworld
  namespace: angi
spec:
  interval: 5m
  url: https://github.com/dmyerscough/angi-helloworld
  ref:
    branch: main
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/charts/