---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: learning-go-api
  namespace: flux-system
spec:
  image: takapiwanashe/sentiment-analysis-frontend
  interval: 1m0s
