---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: audience # Unique name of the release. This can usually be the same as the chart/service
  namespace: learning-go-api # Namespace to install this release into
  labels:
    chart: audience # Unique name
  annotations:
    fluxcd.io/automated: "true" # This annotation instructs the flux app to watch dockerhub for new images that matches the pattern defined below.
    filter.fluxcd.io/chart-image: glob:*-alpha* # The pattern
spec:
  # This section indicates the source of the chart to be used.
  chart:
    git: git@github.com:leadhomesa/synapse-dev.git
    ref: master
    path: charts/audience # Usually only this needs updating
  releaseName: audience # Unique name as above
  values:
    image: leadhomesa/audience-service:5.2.0-alpha373 # Docker image and tag to use in this release. This is what will be updated by flux when a new image becomes available

    ingress:
      enabled: true
      #leadhomedev  OLRiapshocCiWi7
      basicAuth: "leadhomedev:$apr1$fBfR4tDW$/a0bp6qYHkSFVP5r.H2mS."
      hosts:
      - audience.develop.leadhome.io

    appsettings:
      json: |-
        {
          ...
        }

    sealedSecrets:
      ...

    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi

    replicaCount: "{{if_eq scaling.currentPreset 'Full' '1' '0'}}"